plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.camerarepair.rtc'
    compileSdk 35

    defaultConfig {
        applicationId 'dev.camerarepair.rtc'
        minSdk 28
        targetSdk 35
        versionCode 301
        versionName '3.0.1'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/LICENSE*', 'META-INF/NOTICE*']
        }
    }
}

dependencies {
    compileOnly project(':xposed-stubs')
}
